name: TBD Pipeline

on:
  push:
    branches: ["main"]
  pull_request: # THÊM DÒNG NÀY ĐỂ CHẠY TEST KHI MỞ PR
    branches: ["main"]

jobs:
  system-check:
    runs-on: ubuntu-latest
    steps:
      - name: Report Info
        run: echo "Kiểm tra code trước khi merge..."

  deploy-prod:
    # Chỉ deploy khi code đã thực sự vào main (sự kiện push)
    if: github.event_name == 'push' 
    needs: system-check
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to Production
        run: echo "🚀 Deploying to Prod..."
